- name: Run deployment script via SSH
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.CPANEL_HOST }}
    username: ${{ secrets.CPANEL_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    debug: true  # Enable verbose logging
    script: |
      cd /home1/lammygkk/buildmax.lammy.life
      git pull origin main
      # Add any additional deployment commands here, such as:
      # composer install
      # php spark migrate
      # npm install
      # npm run build
