name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y php-cli php-mbstring php-xml

    - name: Deploy to cPanel
      env:
        HOST: ${{ secrets.CPANEL_HOST }}
        USER: ${{ secrets.CPANEL_USER }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avzc --delete --exclude='.git' ./ $USER@$HOST:/path/to/public_html